// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pb/routing.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortestPathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        int64                  `protobuf:"varint,1,opt,name=source,proto3" json:"source,omitempty"`
	Target        int64                  `protobuf:"varint,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortestPathRequest) Reset() {
	*x = ShortestPathRequest{}
	mi := &file_pb_routing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortestPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortestPathRequest) ProtoMessage() {}

func (x *ShortestPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_routing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortestPathRequest.ProtoReflect.Descriptor instead.
func (*ShortestPathRequest) Descriptor() ([]byte, []int) {
	return file_pb_routing_proto_rawDescGZIP(), []int{0}
}

func (x *ShortestPathRequest) GetSource() int64 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *ShortestPathRequest) GetTarget() int64 {
	if x != nil {
		return x.Target
	}
	return 0
}

type PathNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Dist          float64                `protobuf:"fixed64,2,opt,name=dist,proto3" json:"dist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathNode) Reset() {
	*x = PathNode{}
	mi := &file_pb_routing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathNode) ProtoMessage() {}

func (x *PathNode) ProtoReflect() protoreflect.Message {
	mi := &file_pb_routing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathNode.ProtoReflect.Descriptor instead.
func (*PathNode) Descriptor() ([]byte, []int) {
	return file_pb_routing_proto_rawDescGZIP(), []int{1}
}

func (x *PathNode) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *PathNode) GetDist() float64 {
	if x != nil {
		return x.Dist
	}
	return 0
}

type ShortestPathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          []*PathNode            `protobuf:"bytes,1,rep,name=path,proto3" json:"path,omitempty"`
	TotalDistance float64                `protobuf:"fixed64,2,opt,name=total_distance,json=totalDistance,proto3" json:"total_distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortestPathResponse) Reset() {
	*x = ShortestPathResponse{}
	mi := &file_pb_routing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortestPathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortestPathResponse) ProtoMessage() {}

func (x *ShortestPathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_routing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortestPathResponse.ProtoReflect.Descriptor instead.
func (*ShortestPathResponse) Descriptor() ([]byte, []int) {
	return file_pb_routing_proto_rawDescGZIP(), []int{2}
}

func (x *ShortestPathResponse) GetPath() []*PathNode {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *ShortestPathResponse) GetTotalDistance() float64 {
	if x != nil {
		return x.TotalDistance
	}
	return 0
}

var File_pb_routing_proto protoreflect.FileDescriptor

const file_pb_routing_proto_rawDesc = "" +
	"\n" +
	"\x10pb/routing.proto\x12\n" +
	"routing.v1\"E\n" +
	"\x13ShortestPathRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\x03R\x06source\x12\x16\n" +
	"\x06target\x18\x02 \x01(\x03R\x06target\"7\n" +
	"\bPathNode\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\x12\x12\n" +
	"\x04dist\x18\x02 \x01(\x01R\x04dist\"g\n" +
	"\x14ShortestPathResponse\x12(\n" +
	"\x04path\x18\x01 \x03(\v2\x14.routing.v1.PathNodeR\x04path\x12%\n" +
	"\x0etotal_distance\x18\x02 \x01(\x01R\rtotalDistance2c\n" +
	"\x0eRoutingService\x12Q\n" +
	"\fShortestPath\x12\x1f.routing.v1.ShortestPathRequest\x1a .routing.v1.ShortestPathResponseB0Z.github.com/tnh-lab/routing-engine-worker/pb;pbb\x06proto3"

var (
	file_pb_routing_proto_rawDescOnce sync.Once
	file_pb_routing_proto_rawDescData []byte
)

func file_pb_routing_proto_rawDescGZIP() []byte {
	file_pb_routing_proto_rawDescOnce.Do(func() {
		file_pb_routing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_routing_proto_rawDesc), len(file_pb_routing_proto_rawDesc)))
	})
	return file_pb_routing_proto_rawDescData
}

var file_pb_routing_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pb_routing_proto_goTypes = []any{
	(*ShortestPathRequest)(nil),  // 0: routing.v1.ShortestPathRequest
	(*PathNode)(nil),             // 1: routing.v1.PathNode
	(*ShortestPathResponse)(nil), // 2: routing.v1.ShortestPathResponse
}
var file_pb_routing_proto_depIdxs = []int32{
	1, // 0: routing.v1.ShortestPathResponse.path:type_name -> routing.v1.PathNode
	0, // 1: routing.v1.RoutingService.ShortestPath:input_type -> routing.v1.ShortestPathRequest
	2, // 2: routing.v1.RoutingService.ShortestPath:output_type -> routing.v1.ShortestPathResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_routing_proto_init() }
func file_pb_routing_proto_init() {
	if File_pb_routing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_routing_proto_rawDesc), len(file_pb_routing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_routing_proto_goTypes,
		DependencyIndexes: file_pb_routing_proto_depIdxs,
		MessageInfos:      file_pb_routing_proto_msgTypes,
	}.Build()
	File_pb_routing_proto = out.File
	file_pb_routing_proto_goTypes = nil
	file_pb_routing_proto_depIdxs = nil
}
